GET http://localhost:3000/books


### 
GET http://localhost:3000/books
/682be638f960668c7d8f35ac


### Create contact
POST http://localhost:3000/books
 HTTP/1.1
content-type: application/json

{
    "_id": "682be638f960668c7d8f35ac",
  "make": "Toyota1",
  "model": "Camry",
  "year": 2015,
  "color": "Yellow",
  "price": "13000",
  "mileage": "4000",
  "ownerId": "682be5e5f960668c7d8f35ab"
}
###

PUT http://localhost:3000/contacts/681f153c9c4757f3776e3ac7 HTTP/1.1
content-type: application/json

{
    "firstName":"John",
    "lastName":"Doe",
    "email":"JohnDoe1@gmail.com",
    "favoriteColor":"Blue",
    "birthday":"06 32 96"
}
###

DELETE http://localhost:3000/contacts/681f153c9c4757f3776e3ac7